name: Release
on:
  push:
    paths:
    - 'djangoWeb/**'
  workflow_dispatch:
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: djangoWeb
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/ncs_djangoweb
          tag_with_ref: true