name: Release
on:
  push:
    paths:
      - 'djangoWeb/**'
  workflow_dispatch:
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Change repo name to lowercase
        uses: ASzc/change-string-case-action@v1
        id: string
        with:
          string: ${{ github.repository }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: djangoWeb
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ncs_djangoweb:latest
            ghcr.io/${{ steps.string.outputs.lowercase }}/ncs_djangoweb:latest