name: Release
on:
  push:
    paths:
      - 'djangoWeb/**'
  workflow_dispatch:
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Change repo name to lowercase
        uses: ASzc/change-string-case-action@v1
        id: string
        with:
          string: ${{ github.repository }}
      - name: Build and push image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: djangoWeb
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ steps.string.outputs.lowercase }}/ncs_djangoweb
          tag_with_ref: true